const MODULE_ID="food";
const F={SATIETY:"satiety",HYDRATION:"hydration",NOTIFIED:"notifiedThresholds",LAST_TIME:"lastWorldTime",FOOD_VALUE:"foodValue",WATER_VALUE:"waterValue"};
const clamp=(n,min=0,max=100)=>Math.min(max,Math.max(min,Number(n)||0));
const setting=k=>game.settings.get(MODULE_ID,k);

function registerSettings(){
 const r=(k,d)=>game.settings.register(MODULE_ID,k,{scope:"world",config:true,...d});
 r("enabled",{name:"FOOD.Settings.Enabled.Name",hint:"FOOD.Settings.Enabled.Hint",type:Boolean,default:true});
 r("hydrationEnabled",{name:"FOOD.Settings.Hydration.Name",hint:"FOOD.Settings.Hydration.Hint",type:Boolean,default:false,requiresReload:true});
 r("hoursToEmpty",{name:"FOOD.Settings.HoursToEmpty.Name",hint:"FOOD.Settings.HoursToEmpty.Hint",type:Number,default:24,range:{min:1,max:168,step:1}});
 r("waterHoursToEmpty",{name:"FOOD.Settings.WaterHoursToEmpty.Name",hint:"FOOD.Settings.WaterHoursToEmpty.Hint",type:Number,default:12,range:{min:1,max:72,step:1}});
 r("thresholds",{name:"FOOD.Settings.Thresholds.Name",hint:"FOOD.Settings.Thresholds.Hint",type:String,default:"50,25,10,0"});
 r("thresholdMessages",{name:"FOOD.Settings.Messages.Name",hint:"FOOD.Settings.Messages.Hint",type:String,default:"50=You start thinking about food.|25=Your stomach growls loudly.|10=Hunger makes it difficult to concentrate.|0=You are starving."});
 r("whisperGM",{name:"FOOD.Settings.WhisperGM.Name",hint:"FOOD.Settings.WhisperGM.Hint",type:Boolean,default:true});
 r("showExactPercent",{name:"FOOD.Settings.ShowPercent.Name",hint:"FOOD.Settings.ShowPercent.Hint",type:Boolean,default:false});
 r("allowPlayerAdjust",{name:"FOOD.Settings.PlayerAdjust.Name",hint:"FOOD.Settings.PlayerAdjust.Hint",type:Boolean,default:true});
 r("applyExhaustion",{name:"FOOD.Settings.Exhaustion.Name",hint:"FOOD.Settings.Exhaustion.Hint",type:Boolean,default:false});
}
function thresholds(){return [...new Set(String(setting("thresholds")).split(",").map(Number).filter(Number.isFinite).map(v=>clamp(v)).sort((a,b)=>b-a))];}
function messages(){const out={};for(const p of String(setting("thresholdMessages")).split("|")){const [k,...m]=p.split("=");if(Number.isFinite(Number(k))&&m.length)out[clamp(k)]=m.join("=").trim();}return out;}
function getValue(actor,key,fallback=100){return clamp(actor.getFlag(MODULE_ID,key)??fallback);}
function stateFor(v){if(v<=0)return"empty";if(v<=10)return"starving";if(v<=25)return"hungry";if(v<=50)return"peckish";if(v<=75)return"comfortable";return"full";}
function canControl(actor){return game.user.isGM||(setting("allowPlayerAdjust")&&actor.isOwner);}
async function setResource(actor,key,next,{notify=true}={}){const old=getValue(actor,key),value=clamp(next);await actor.setFlag(MODULE_ID,key,value);if(key===F.SATIETY&&notify)await processThresholds(actor,old,value);Hooks.callAll("foodResourceChanged",actor,key,old,value);}
async function changeResource(actor,key,delta,options){return setResource(actor,key,getValue(actor,key)+Number(delta||0),options);}
async function processThresholds(actor,oldValue,newValue){let notified=foundry.utils.deepClone(actor.getFlag(MODULE_ID,F.NOTIFIED)??{});for(const t of thresholds())if(newValue>t)delete notified[t];const crossed=thresholds().filter(t=>oldValue>t&&newValue<=t&&!notified[t]);if(crossed.length){const t=crossed[crossed.length-1];notified[t]=true;await actor.setFlag(MODULE_ID,F.NOTIFIED,notified);await sendHungerMessage(actor,t,newValue);if(t===0&&setting("applyExhaustion"))await addExhaustion(actor);}else await actor.setFlag(MODULE_ID,F.NOTIFIED,notified);}
async function sendHungerMessage(actor,t,value){const msg=messages()[t]??game.i18n.format("FOOD.Chat.DefaultHunger",{name:actor.name});const exact=setting("showExactPercent")?`<div class="food-chat-percent">${game.i18n.localize("FOOD.Satiety")}: ${Math.round(value)}%</div>`:"";const owners=game.users.filter(u=>!u.isGM&&u.active&&actor.testUserPermission(u,"OWNER")).map(u=>u.id);const recipients=[...new Set([...owners,...(setting("whisperGM")?ChatMessage.getWhisperRecipients("GM").map(u=>u.id):[])])];await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<section class="food-chat"><strong>${game.i18n.localize("FOOD.Chat.Hunger")}</strong><p>${foundry.utils.escapeHTML(msg)}</p>${exact}</section>`,whisper:recipients});}
async function addExhaustion(actor){const path="system.attributes.exhaustion",current=foundry.utils.getProperty(actor,path);if(typeof current==="number")await actor.update({[path]:Math.min(6,current+1)});}
function stomachSvg(value,id){const pct=clamp(value),fillY=155-pct*1.15,state=stateFor(pct);return `<svg class="food-stomach-svg state-${state}" viewBox="0 0 170 180" role="img" aria-label="${game.i18n.format("FOOD.Widget.Aria",{value:Math.round(pct)})}"><defs><clipPath id="food-stomach-clip-${id}"><path d="M91 24c-2 25 3 38 19 47 29 17 36 47 23 72-14 28-52 27-74 12-25-17-34-48-21-74 8-16 23-25 34-35 8-8 11-16 12-25z"/></clipPath><linearGradient id="food-fill-${id}" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="currentColor"/><stop offset="1" stop-color="color-mix(in srgb, currentColor 65%, white)"/></linearGradient></defs><path class="food-stomach-shadow" d="M91 24c-2 25 3 38 19 47 29 17 36 47 23 72-14 28-52 27-74 12-25-17-34-48-21-74 8-16 23-25 34-35 8-8 11-16 12-25z"/><g clip-path="url(#food-stomach-clip-${id})"><rect class="food-stomach-liquid" x="20" y="${fillY}" width="130" height="150" fill="url(#food-fill-${id})"/><path class="food-stomach-wave" d="M20 ${fillY} Q42 ${fillY-5} 64 ${fillY} T108 ${fillY} T152 ${fillY}"/></g><path class="food-stomach-outline" d="M91 24c-2 25 3 38 19 47 29 17 36 47 23 72-14 28-52 27-74 12-25-17-34-48-21-74 8-16 23-25 34-35 8-8 11-16 12-25z"/><path class="food-esophagus" d="M85 6c0 9 0 17-1 25M96 7c-1 10-2 18-5 27"/></svg>`;}
function widgetHtml(actor){const s=getValue(actor,F.SATIETY),h=getValue(actor,F.HYDRATION),id=actor.id.replace(/[^a-zA-Z0-9]/g,""),exact=setting("showExactPercent")||game.user.isGM;return `<section class="food-widget" data-actor-id="${actor.id}"><header><i class="fa-solid fa-bowl-food"></i>${game.i18n.localize("FOOD.Title")}</header><div class="food-resource"><div class="food-visual">${stomachSvg(s,id)}<span class="food-state">${game.i18n.localize(`FOOD.State.${stateFor(s)}`)}</span>${exact?`<b>${Math.round(s)}%</b>`:""}</div><div class="food-actions"><button type="button" data-food-action="eat"><i class="fa-solid fa-utensils"></i>${game.i18n.localize("FOOD.Actions.Eat")}</button><button type="button" data-food-action="adjust"><i class="fa-solid fa-sliders"></i>${game.i18n.localize("FOOD.Actions.Adjust")}</button></div></div>${setting("hydrationEnabled")?`<div class="food-hydration"><i class="fa-solid fa-droplet"></i><span>${game.i18n.localize("FOOD.Hydration")}</span><progress max="100" value="${h}"></progress>${exact?`<b>${Math.round(h)}%</b>`:""}<button type="button" data-food-action="drink"><i class="fa-solid fa-glass-water"></i></button></div>`:""}</section>`;}
function injectWidget(app,html){if(!setting("enabled"))return;const actor=app.actor??app.document;if(!(actor instanceof Actor)||actor.type!=="character")return;const root=html instanceof HTMLElement?html:html?.[0];if(!root||root.querySelector(".food-widget"))return;const target=root.querySelector(".sheet-body, .window-content, form")??root;target.insertAdjacentHTML("afterbegin",widgetHtml(actor));bindWidget(root.querySelector(".food-widget"),actor);}
function bindWidget(el,actor){el?.addEventListener("click",async e=>{const b=e.target.closest("[data-food-action]");if(!b||!canControl(actor))return;if(b.dataset.foodAction==="eat")await openConsumeDialog(actor,"food");if(b.dataset.foodAction==="drink")await openConsumeDialog(actor,"water");if(b.dataset.foodAction==="adjust")await openAdjustDialog(actor);});}
async function openConsumeDialog(actor,type){const flag=type==="food"?F.FOOD_VALUE:F.WATER_VALUE,items=actor.items.filter(i=>i.type==="consumable"&&Number(i.getFlag(MODULE_ID,flag))>0),options=items.map(i=>`<option value="${i.id}">${foundry.utils.escapeHTML(i.name)} (+${Number(i.getFlag(MODULE_ID,flag))}%)</option>`).join("");const content=`<form class="food-dialog"><p>${game.i18n.localize(items.length?"FOOD.Dialog.Choose":"FOOD.Dialog.NoItems")}</p>${items.length?`<select name="itemId">${options}</select>`:""}<hr><label>${game.i18n.localize("FOOD.Dialog.Manual")}<input type="number" name="manual" min="0" max="100" step="1" value="0"></label></form>`;await foundry.applications.api.DialogV2.wait({window:{title:game.i18n.localize(type==="food"?"FOOD.Actions.Eat":"FOOD.Actions.Drink")},content,buttons:[{action:"consume",label:game.i18n.localize("FOOD.Actions.Consume"),icon:"fa-solid fa-check",default:true,callback:async(_e,b)=>{const form=b.form,item=actor.items.get(form.elements.itemId?.value),manual=Number(form.elements.manual?.value||0);let amount=manual;if(item){amount+=Number(item.getFlag(MODULE_ID,flag)||0);const q=Number(foundry.utils.getProperty(item,"system.quantity")??1);if(q>0)await item.update({"system.quantity":Math.max(0,q-1)});}if(amount>0)await changeResource(actor,type==="food"?F.SATIETY:F.HYDRATION,amount,{notify:false});}},{action:"cancel",label:game.i18n.localize("Cancel")}]});}
async function openAdjustDialog(actor){const content=`<form class="food-dialog"><label>${game.i18n.localize("FOOD.Satiety")}<input name="satiety" type="number" min="0" max="100" value="${getValue(actor,F.SATIETY)}"></label>${setting("hydrationEnabled")?`<label>${game.i18n.localize("FOOD.Hydration")}<input name="hydration" type="number" min="0" max="100" value="${getValue(actor,F.HYDRATION)}"></label>`:""}</form>`;await foundry.applications.api.DialogV2.wait({window:{title:game.i18n.localize("FOOD.Actions.Adjust")},content,buttons:[{action:"save",label:game.i18n.localize("Save"),default:true,callback:async(_e,b)=>{await setResource(actor,F.SATIETY,b.form.elements.satiety.value);if(setting("hydrationEnabled"))await setResource(actor,F.HYDRATION,b.form.elements.hydration.value,{notify:false});}},{action:"cancel",label:game.i18n.localize("Cancel")}]});}
function addItemConfig(app,html){const item=app.item??app.document;if(!(item instanceof Item)||item.type!=="consumable")return;const root=html instanceof HTMLElement?html:html?.[0],form=root?.querySelector("form")??root;if(!form||form.querySelector(".food-item-config"))return;form.insertAdjacentHTML("beforeend",`<fieldset class="food-item-config"><legend>${game.i18n.localize("FOOD.ItemConfig.Title")}</legend><label>${game.i18n.localize("FOOD.ItemConfig.FoodValue")}<input type="number" name="flags.${MODULE_ID}.${F.FOOD_VALUE}" min="0" max="100" step="1" value="${Number(item.getFlag(MODULE_ID,F.FOOD_VALUE)||0)}"></label>${setting("hydrationEnabled")?`<label>${game.i18n.localize("FOOD.ItemConfig.WaterValue")}<input type="number" name="flags.${MODULE_ID}.${F.WATER_VALUE}" min="0" max="100" step="1" value="${Number(item.getFlag(MODULE_ID,F.WATER_VALUE)||0)}"></label>`:""}</fieldset>`);}
async function processElapsedTime(worldTime,delta){if(!setting("enabled")||!game.user.isGM||delta<=0)return;const hours=delta/3600;if(!Number.isFinite(hours)||hours<=0)return;const foodLoss=100/Math.max(1,setting("hoursToEmpty"))*hours,waterLoss=100/Math.max(1,setting("waterHoursToEmpty"))*hours;for(const actor of game.actors.filter(a=>a.type==="character")){await changeResource(actor,F.SATIETY,-foodLoss);if(setting("hydrationEnabled"))await changeResource(actor,F.HYDRATION,-waterLoss,{notify:false});await actor.setFlag(MODULE_ID,F.LAST_TIME,worldTime);}}
Hooks.once("init",()=>{registerSettings();console.log(`${MODULE_ID} | Initialized`);});
Hooks.once("ready",()=>{game.modules.get(MODULE_ID).api={getSatiety:a=>getValue(a,F.SATIETY),setSatiety:(a,v,o)=>setResource(a,F.SATIETY,v,o),changeSatiety:(a,d,o)=>changeResource(a,F.SATIETY,d,o),getHydration:a=>getValue(a,F.HYDRATION),setHydration:(a,v,o)=>setResource(a,F.HYDRATION,v,o)};if(game.modules.get("simple-timekeeping")?.active)ui.notifications.info(game.i18n.localize("FOOD.Notifications.TimekeepingDetected"));});
Hooks.on("renderActorSheet",injectWidget);Hooks.on("renderActorSheetV2",injectWidget);Hooks.on("renderItemSheet",addItemConfig);Hooks.on("renderItemSheetV2",addItemConfig);Hooks.on("updateWorldTime",processElapsedTime);Hooks.on("updateActor",actor=>{if(actor.type==="character")actor.sheet?.render(false);});
